server:
  port: 8762

spring:
  application:
    name: service-provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: service-provider
  #设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
  sleuth:
    sampler:
      probability: 1